gpu_id: '0'
log_wandb: False
logging:
  level: DEBUG

# mamba4POI settings
hidden_size: 128                 # (int) Number of features in the hidden state. 
num_layers: 1                   # (int) Number of Mamba layers.
dropout_prob: 0.2               # (float) Dropout rate.
loss_type: 'BPR'                 # (str) Type of loss function. Range in ['BPR', 'CE'].
d_state: 32                     # (int) SSM state expansion factor
d_conv: 4                       # (int) Local convolution width
expand: 2                       # (int) Block expansion factor


# Save Directory Settings
checkpoint_dir: 'SavedData'
save_dataloaders: True
dataloaders_save_path: ''  # 留空，代码会使用默认路径
save_dataset: True                 # 启用保存dataset功能
dataset_save_path: 'SavedData/foursquare_NYC-FourSquare.pth'  
seed: 42  # 设置一个默认种子



#Dataset Settings
USER_ID_FIELD: user_id
ITEM_ID_FIELD: venue_id
TIME_FIELD: timestamp
LABEL_FIELD: label

load_col:
    inter: [user_id, venue_id,venue_id_list,timestamp]
    item: [venue_id,latitude, longitude,venue_category_id]


LIST_SUFFIX: "_list"
MAX_ITEM_LIST_LENGTH: 100
ITEM_LIST_LENGTH_FIELD: venue_seq_len


#Dataloader&Sampler
dataset: foursquare_NYC
Use_CustomDataset: True  # 使用自定义的 FourSquareDataset 数据集类
Use_CustomSampler: False
Use_CustomDataloader: True
repeatable: True  #进行阶段隔离
NEG_PREFIX: "neg_"


# training settings
epochs: 200
train_batch_size: 100
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10
single_spec: True

train_neg_sample_args: 
  distribution: "popularity"
  alpha: 0.5
  dynamic: False
  sample_num: 5

eval_args:
  order: TO 
  spilt: 
    RS: [0.7,0.1,0.2]
  gourp_by: user_id
  max_seq_len: 20 
  mode:
    val: labeled
    test: labeled
  metrics: ["Recall@1", "Recall@20","MRR@20"]  # 使用你需要的评估指标

# evalution settings
metrics: ['Recall', 'MRR']
valid_metric: MRR@20
eval_batch_size: 100
weight_decay: 0.0
topk: [20]
# 评估设置，确保为顺序推荐任务配置时间顺序




